feat(hooks): add input parameter to callbacks
TheEdoRan/next-safe-action pull request #17
Opened 2023-08-30 17:56 UTC by alerosa

Hi Edoardo!
First of all, thanks a lot for this library, it's super handy when working with server actions :+1: 

I've opened a PR to add another parameter to the `onSuccess` and `onError` callbacks, which contains the original input as it's sent to the server. This is handy whenever the server is not returning all the expected data, or the error callback is called, but the client still needs the input data to do something (for instance, render a toast containing a message).

Example:

```ts
const { execute } = useAction(
  sendEmail,
  {
    onError: (_, _, input) => {
      toast({
        title: `Error while sending an email to: ${input.email}`,
      });
    },
  },
);

const handleSendEmal = (email: string) => {
  execute({ email: email });
};
```

Without the `input` parameter, there is no way for me to get access to the payload that was sent to the server unless I add a state to my component to keep track of it, which is far less convenient then the solution above.

This idea can also be found in libraries like [TanStack Query](https://tanstack.com/query/v4/docs/react/reference/useMutation) where they have this argument called `variables` on their callbacks which I believe is basically the same thing.

Please let me know what you think :relaxed:

2023-09-06 12:41 UTC, TheEdoRan commented
Thank you for this PR. I think it's pretty useful to have `input` as param of `onSuccess` and `onError` callbacks, so this change is much appreciated!

Just one thing though: please document it in the lib's README file, so users will know about this. Thank you!

2023-09-12 14:43 UTC, TheEdoRan requested changes
Awesome, thank you very much for your work. Just one little thing though, please restore the original README_v2 file content, as it's just there for the previous lib version, which is already published. You just need to update the README file for the current version (3.x.x). Grazie :)

2023-09-15 08:04 UTC, alerosa commented
> Awesome, thank you very much for your work. Just one little thing though, please restore the original README_v2 file content, as it's just there for the previous lib version, which is already published. You just need to update the README file for the current version (3.x.x). Grazie :)

Done :slightly_smiling_face:

2023-09-18 21:46 UTC, TheEdoRan approved these changes

2023-09-18 21:48 UTC, merged